require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

target 'sporty_note' do
  pod 'FirebaseCore', :modular_headers => true
  config = use_native_modules!
  pod 'GoogleUtilities', :modular_headers => true

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    #:flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'sporty_noteTests' do
    inherit! :complete
    # Pods for testing
  end

  use_flipper!({ 'Flipper-Folly' => '2.6.7', 'OpenSSL-Universal' => '1.1.180', 'Flipper' => '0.125.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
